export {SoftwarePage} from "./SoftwarePage";
export {HardwarePage}from "./HardwarePage";
export {ProfilePage} from "./ProfilePage";
export {PleaseVerifyEmailPage} from "./PleaseVerifyEmail";
export { PasswordResetLandingPage} from "./PasswordResetLandingPage";
export { EmailVerificationLandingPage} from "./EmailVerificationLandingPage";
export { ForgotPasswordPage} from "./ForgotPasswordPage";
export {SocialMediaMarketingPage} from "./SocialmediaMarketing/SocialmediaMarketing";
export {SecondSocialMediaPage} from "./SocialmediaMarketing/SecondPage";
export {BusinessManagementPage} from "./Featured/BusinessManagement";
export { DataStructuresPage} from "./Featured/DataStructures";
export {DatabaseManagementSystemPage } from "./Featured/DbManagementSystems";
export {GraphicDesignPage} from "./Featured/GraphicDesign";
export {WebDevelopmentPage } from "./Featured/WebDevelopement";
export {WebTechnologiesPage } from "./Featured/WebTechnologies";
export { EbooksPage} from "./e-Library/EbooksPage";
export { ForumPage} from "./e-Library/ForumPage";
export {TutorialsPage } from "./e-Library/Tutorials";
export {ContactPage} from "./ContactPage";
export { RegisterPage } from "./Forms/Register";
export {LoginPage} from "./Forms/LogIn";
export {AboutPage} from "./AboutPage";
export {HomePage} from "./HomePage";
export {NotFoundPage} from "./NotFoundPage";

export {ArticlesListPage} from "./ArticlesListPage";
export { ArticlePage } from "./ArticlePage";